baseURL: 'https://tnwei.github.io/'
languageCode: 'en-us'
title: 'Tan Nian Wei'
theme: 'PaperMod'

# Fill out when there's more stuff
menu:
  main:
    - identifier: Writing
      name: Writing
      url: /writing/ # using the archives feature for this allows showing timeline
#   - identifier: about
#     name: About
#     url: /about/


params:
  env: 'production'
  # ShowBreadCrumbs: true # e.g. Home -> Writing
  # ShowToc: true
  # author: 'Tan Nian Wei' # kinda self-evident isn't it?
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: false
  ShowShareButtons: true
  DateFormat: 'Jan 2, 2006 Mon'
  disableSpecial1stPost: true
  
  comments: true # edit in layouts/partial/comments.html

  assets:
    disableHLJS: true # use chroma instead

  homeInfoParams:
    Title: Hi, I'm Nian Wei
    Content: |
      ~ I think machine learning is cool
      
      ~ Currently building applied machine learning applications with PETRONAS Research

    # TODO: Add third line eventually. Markdown accepted  


  socialIcons:
    - name: github
      url: "https://github.com/tnwei"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/13095028/tnwei"
  
markup:
  highlight:
    # anchorLineNos: true   # underline line nos, looks nice actually
    codeFences: true
    guessSyntax: true
    # lineNos: true         # not useful most of the time, leave off
    # noClasses: false      # this checks language, leave true
    style: monokai

