baseURL: 'https://tnwei.github.io/'
languageCode: 'en-us'
title: 'Tan Nian Wei'
theme: 'PaperMod'

# Fill out when there's more stuff
menu:
  main:
    - identifier: Writing
      name: Writing
      url: /writing/ # using the archives feature for this allows showing timeline
      weight: 10 # Higher weight is on the right
    - identifier: Resume
      name: Resume
      url: https://drive.google.com/file/d/1kWKGkamiCd7RZLssEBy3b-FT3r0jpwha/view?usp=sharing
      weight: 50
    - identifier: About
      name: About
      url: /about/
      weight: 60


params:
  env: 'production'
  # ShowBreadCrumbs: true # e.g. Home -> Writing
  # ShowToc: true
  # author: 'Tan Nian Wei' # kinda self-evident isn't it?
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: false
  ShowShareButtons: false
  DateFormat: 'Jan 2, 2006 Mon'
  disableSpecial1stPost: true
 
  defaultTheme: light
  
  # comments JS can't change dynamically with theme
  # disable until I figure out how
  disableThemeToggle: true  

  comments: true # edit in layouts/partial/comments.html

  assets:
    disableHLJS: true # use chroma instead

  homeInfoParams:
    Title: Hi, I'm Nian Wei
    Content: |
      ~ Tech co-founder @ V-Cred / ex-PETRONAS Research

      ~ Based in Kuala Lumpur, Malaysia


  socialIcons:
    - name: github
      url: "https://github.com/tnwei"
    - name: linkedin
      url: "https://www.linkedin.com/in/nianweitan"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/13095028/tnwei"
  
markup:
  highlight:
    # anchorLineNos: true   # underline line nos, looks nice actually
    codeFences: true
    guessSyntax: true
    # lineNos: true         # not useful most of the time, leave off
    # noClasses: false      # this checks language, leave true
    style: monokai

